/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Annotation: typeof import('./src/components/Annotation.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    BaseSelect: typeof import('./src/components/BaseSelect.vue')['default']
    BaseSwitch: typeof import('./src/components/BaseSwitch.vue')['default']
    EditorBlock: typeof import('./src/components/EditorBlock.vue')['default']
    ExportOptions: typeof import('./src/components/ExportOptions.vue')['default']
    IconAnalytics: typeof import('./src/components/IconAnalytics.vue')['default']
    IconCheck: typeof import('./src/components/IconCheck.vue')['default']
    IconChevronDown: typeof import('./src/components/IconChevronDown.vue')['default']
    IconClipboard: typeof import('./src/components/IconClipboard.vue')['default']
    IconClipboardLink: typeof import('./src/components/IconClipboardLink.vue')['default']
    IconClose: typeof import('./src/components/IconClose.vue')['default']
    IconCoffee: typeof import('./src/components/IconCoffee.vue')['default']
    IconDownload: typeof import('./src/components/IconDownload.vue')['default']
    IconGithub: typeof import('./src/components/IconGithub.vue')['default']
    IconTwitter: typeof import('./src/components/IconTwitter.vue')['default']
    IconTwitterCircle: typeof import('./src/components/IconTwitterCircle.vue')['default']
    'IPh:e': typeof import('~icons/ph/e')['default']
    'IPh:eye': typeof import('~icons/ph/eye')['default']
    'IPh:eye-': typeof import('~icons/ph/eye-')['default']
    'IPh:eyeClosed': typeof import('~icons/ph/eye-closed')['default']
    'IPh:eyeOf': typeof import('~icons/ph/eye-of')['default']
    'IPh:eyeOff': typeof import('~icons/ph/eye-off')['default']
    'IPh:plus': typeof import('~icons/ph/plus')['default']
    NoteBlock: typeof import('./src/components/NoteBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheEditor: typeof import('./src/components/TheEditor.vue')['default']
    TheEditorFrame: typeof import('./src/components/TheEditorFrame.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheFrameBackground: typeof import('./src/components/TheFrameBackground.vue')['default']
    TheFrameResizer: typeof import('./src/components/TheFrameResizer.vue')['default']
    TheParticlesBackground: typeof import('./src/components/TheParticlesBackground.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
    TheToolbar: typeof import('./src/components/TheToolbar.vue')['default']
  }
}
