/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'IFa6Brands:github': typeof import('~icons/fa6-brands/github')['default']
    'IFa6Brands:xTwitter': typeof import('~icons/fa6-brands/x-twitter')['default']
    'IPh:coffee': typeof import('~icons/ph/coffee')['default']
    'IPh:dotsThreeBold': typeof import('~icons/ph/dots-three-bold')['default']
    'IPh:eye': typeof import('~icons/ph/eye')['default']
    'IPh:eyeClosed': typeof import('~icons/ph/eye-closed')['default']
    'IPh:pencilSimple': typeof import('~icons/ph/pencil-simple')['default']
    'IPh:plusBold': typeof import('~icons/ph/plus-bold')['default']
    'IPh:shareNetwork': typeof import('~icons/ph/share-network')['default']
    'IPh:trashSimple': typeof import('~icons/ph/trash-simple')['default']
    'IPh:warning': typeof import('~icons/ph/warning')['default']
    'IRadixIcons:chevronDown': typeof import('~icons/radix-icons/chevron-down')['default']
    'IRadixIcons:clipboard': typeof import('~icons/radix-icons/clipboard')['default']
    'IRadixIcons:download': typeof import('~icons/radix-icons/download')['default']
    'IRadixIcons:minus': typeof import('~icons/radix-icons/minus')['default']
    'IRadixIcons:plus': typeof import('~icons/radix-icons/plus')['default']
  }
}
